<?xml version = '1.0' encoding = 'utf-8'?>
<!--Generated by Oracle BI Publisher 10.1.3.4.1-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, concat($_XDODFOVERRIDE,'',$_XDOCURMASKS,'',$_XDONFSEPARATORS))"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0" margin-left="66.6pt" margin-right="66.6pt" page-height="792.0pt" page-width="612.0pt" margin-top="36.0pt" margin-bottom="36.0pt">
               <fo:region-before region-name="region-header" extent="36.0pt"/>
               <fo:region-body region-name="region-body" margin-top="36.0pt" margin-bottom="36.0pt"/>
               <fo:region-after region-name="region-footer" extent="36.0pt" display-align="after"/>
            </fo:simple-page-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0">
            <fo:title>RTF Template</fo:title>
            <xsl:variable name="_PW" select="number(612.0)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(792.0)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header"/>
            <fo:static-content flow-name="region-footer"/>
            <fo:flow flow-name="region-body">
               <fo:block padding-bottom="0.25pt" padding-top="0.25pt">
                  <fo:table start-indent="0.0pt" style-id="ts15" style-name="Table Grid" xdofo:table-summary="Template Table 1" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="90.85pt"/>
                     <fo:table-column column-width="76.45pt"/>
                     <fo:table-column column-width="103.45pt"/>
                     <fo:table-column column-width="94.5pt"/>
                     <fo:table-column column-width="113.55pt"/>
                     <fo:table-body>
                        <fo:table-row>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#f2f2f2">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Segoe UI Light" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Code</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#f2f2f2">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Segoe UI Light" white-space-collapse="false" font-size="10.0pt" font-weight="bold">ID</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#f2f2f2">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Segoe UI Light" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Description</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#f2f2f2">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Segoe UI Light" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Address 1</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt" background-color="#f2f2f2">
                              <fo:block orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt">
                                 <fo:inline height="10.0pt" font-family="Segoe UI Light" white-space-collapse="false" font-size="10.0pt" font-weight="bold">Address 2</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
                        <xsl:variable name="_XDOFOTOTAL" select="count(.//G_1)"/>
                        <xsl:for-each select=".//G_1" xdofo:ctx="3">
                           <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                           <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                           <fo:table-row xdofo:repeat="R">
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="G_1, AGENT_CODE" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                    <fo:inline height="10.0pt" font-family="Segoe UI Light" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//AGENT_CODE" xdofo:field-name="AGENT_CODE"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AGENT_ID" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Segoe UI Light" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//AGENT_ID" xdofo:field-name="AGENT_ID"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AGENT_DESCRIPTION" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Segoe UI Light" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//AGENT_DESCRIPTION" xdofo:field-name="AGENT_DESCRIPTION"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AGENT_ADDRESS_1" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0.0pt">
                                    <fo:inline height="10.0pt" font-family="Segoe UI Light" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//AGENT_ADDRESS_1" xdofo:field-name="AGENT_ADDRESS_1"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                              <fo:table-cell padding-start="5.15pt" vertical-align="top" border-bottom="0.5pt solid #000000" border-end-color="#000000" padding-top="0.0pt" border-end-style="solid" border-start-color="#000000" padding-end="5.15pt" number-columns-spanned="1" border-top="0.5pt solid #000000" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                                 <fo:block xdofo:xliff-note="AGENT_ADDRESS_2, END" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="0.0pt" text-align="start" padding-bottom="0.0pt" end-indent="0.0pt" padding-top="0.0pt" height="0pt">
                                    <fo:inline height="10.0pt" font-family="Segoe UI Light" white-space-collapse="false" font-size="10.0pt">
                                       <xsl:value-of select=".//AGENT_ADDRESS_2" xdofo:field-name="AGENT_ADDRESS_2"/>
                                    </fo:inline>
                                 </fo:block>
                              </fo:table-cell>
                           </fo:table-row>
                        </xsl:for-each>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block xdofo:line-spacing="multiple:12.95pt" orphans="2" widows="2" linefeed-treatment="preserve" start-indent="5.4pt" text-align="start" padding-bottom="8.0pt" end-indent="5.4pt" padding-top="0.0pt" height="0.0pt" font-size="11.0pt" font-family="Calibri">
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
</xsl:stylesheet>
