<?xml version = '1.0' encoding = 'utf-8'?>
<!--Generated by Oracle BI Publisher 10.1.3.4.1-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <fo:layout-master-set/>
      </fo:root>
   </xsl:template>
</xsl:stylesheet>
